services:
  - type: web
    name: attendx-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180 --workers 1 --bind 0.0.0.0:$PORT
    healthCheckPath: /ping
    envVars:
      - key: RENDER
        value: "true"
      - key: DATABASE_PATH
        value: /tmp/attendx.db
